//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Demo
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 联系人表  
    /// </summary> 
    public partial class Contacts
    {
    /// <summary>  
    /// 主键  
    /// </summary> 
        public int Id { get; set; }
    /// <summary>  
    /// 用户名  
    /// </summary> 
        public string UserName { get; set; }
    /// <summary>  
    /// 手机  
    /// </summary> 
        public string Tel { get; set; }
    /// <summary>  
    /// 手机2  
    /// </summary> 
        public string Tel1 { get; set; }
    /// <summary>  
    /// 地址  
    /// </summary> 
        public string Address { get; set; }
    }
}
