//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class weixinDBEntities : DbContext
    {
        public weixinDBEntities()
            : base("name=weixinDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Contacts> Contacts { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<ProductCategorys> ProductCategorys { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<WeiXinUserInfo> WeiXinUserInfo { get; set; }
        public DbSet<WXUserBaseInfo> WXUserBaseInfo { get; set; }
        public DbSet<WXUserGroup> WXUserGroup { get; set; }
        public DbSet<ProductImgs> ProductImgs { get; set; }
    
        public virtual int proc_CreateUser(string username, string password, string truename, Nullable<int> role)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var truenameParameter = truename != null ?
                new ObjectParameter("truename", truename) :
                new ObjectParameter("truename", typeof(string));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_CreateUser", usernameParameter, passwordParameter, truenameParameter, roleParameter);
        }
    
        public virtual int proc_DelUser(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_DelUser", idParameter);
        }
    
        public virtual int proc_UpdateUser(Nullable<int> id, string username)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_UpdateUser", idParameter, usernameParameter);
        }
    
        public virtual int proc_User(Nullable<int> id, ObjectParameter truename, ObjectParameter username)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_User", idParameter, truename, username);
        }
    
        public virtual int proc_User_count()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_User_count");
        }
    
        public virtual int proc_User_count_username(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("proc_User_count_username", usernameParameter);
        }
    }
}
