//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Demo
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 订单表  
    /// </summary> 
    public partial class Orders
    {
    /// <summary>  
    /// 主键  
    /// </summary> 
        public int Id { get; set; }
    /// <summary>  
    /// 订单编号  
    /// </summary> 
        public string Number { get; set; }
    /// <summary>  
    /// 商品名称  
    /// </summary> 
        public string ProductName { get; set; }
    /// <summary>  
    /// 商品价格  
    /// </summary> 
        public Nullable<decimal> Price { get; set; }
    /// <summary>  
    /// 用户id  
    /// </summary> 
        public Nullable<int> UserId { get; set; }
    /// <summary>  
    /// 创建日期  
    /// </summary> 
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
