//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Demo
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 角色表  
    /// </summary> 
    public partial class Role
    {
    /// <summary>  
    /// 主键id  
    /// </summary> 
        public int Id { get; set; }
    /// <summary>  
    /// 角色名称  
    /// </summary> 
        public string Name { get; set; }
    /// <summary>  
    /// 角色描述  
    /// </summary> 
        public string Instruction { get; set; }
    }
}
