//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Demo
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 粉丝表  
    /// </summary> 
    public partial class WXUserBaseInfo
    {
    /// <summary>  
    /// 主键id  
    /// </summary> 
        public int Id { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public Nullable<int> subscribe { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public string openid { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public string nickname { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public Nullable<int> sex { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public string language { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public string city { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public string province { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public string country { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public string headimgurl { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public string subscribe_time { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public string remark { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public Nullable<int> groupid { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public Nullable<int> WXUserId { get; set; }
    /// <summary>  
    ///   
    /// </summary> 
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
