//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace T4Demo
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>  
    /// 用户分组表  
    /// </summary> 
    public partial class WXUserGroup
    {
    /// <summary>  
    /// 主键  
    /// </summary> 
        public int Id { get; set; }
    /// <summary>  
    /// 分组id  
    /// </summary> 
        public Nullable<int> GroupId { get; set; }
    /// <summary>  
    /// 分组名称  
    /// </summary> 
        public string Name { get; set; }
    /// <summary>  
    /// 数量  
    /// </summary> 
        public Nullable<int> Count { get; set; }
    /// <summary>  
    /// 创建日期  
    /// </summary> 
        public Nullable<System.DateTime> CreateDate { get; set; }
    /// <summary>  
    /// 公众号id  
    /// </summary> 
        public Nullable<int> WXUserId { get; set; }
    }
}
